### ISSUE TITLE
org1 file

### ISSUE THREAD

**Issue by youngmanuit** [IBM/assetTracking#3]
Where can i find the org1 file ?

**Comment by odrodrig** [comment]
@youngmanuit "org1" is a directory at the top level of the repo. The smart contract and all application files are in that directory. You can view the contents of the org1 directory [here](https://github.com/IBM/assetTracking/tree/master/org1). Hope that answers the question. If not, could you provide more information on where in the instructions you are?

**Comment by youngmanuit** [comment]
This means before I have taken this step https://github.com/IBM/assetTracking#creating-the-logspout-container, I have to clone this repo to my machine, right? And Can you explain to me why this error occurred when I tried to start LOCAL FABRIC OPS 
![image](https://user-images.githubusercontent.com/33368418/58619374-01c51a80-82ef-11e9-8ad1-51f0947ce81d.png)  ?
Thank you very much!

**Comment by ljbennett62** [comment]
@youngmanuit - you definitely should clone the repo.  Q for you - not sure what you mean "start LOCAL_FABRIC_OPS" ? - what command are are you actually issuing?

**Comment by youngmanuit** [comment]
Thanks @ljbennett62 , yes, i want to start LOCAL_FABRIC_OPS. But i started it already.
