### ISSUE TITLE
getQuerySelector vs composite keys

### ISSUE THREAD

**Issue by varunagarwal315** [IBM/assetTracking#4]
Hi, I noticed for the queries `querySelector` is used. As [per this document](https://fabric-shim.github.io/release-1.4/fabric-shim.ChaincodeStub.html#getQueryResult__anchor) it should only be used for read queries and not during transactions that may update the chaincode. However since the queries used here are quite basic and during read only transactions there is no issue, but as a new dev, I wanted to understand if there is any reason `compositeKeys` has not been used?

**Comment by odrodrig** [comment]
I used getQueryResult because I was only reading from the world state and, since the local network is running couchDB, I wanted to have the possibility of running "rich" queries.
