### ISSUE TITLE
Register a new device

### ISSUE THREAD

**Issue by youngmanuit** [IBM/assetTracking#5]
i'm working on this step https://github.com/IBM/assetTracking#register-a-new-device , but i get an error like this: 
![image](https://user-images.githubusercontent.com/33368418/60076185-21662c00-9751-11e9-99c6-6d6513bd1bcf.png)
Have any solution to resolve it ?
 Looking forward to your help! Thank you so much

**Comment by odrodrig** [comment]
Are you still getting this error? Looks like a temporary error from the website.
