### ISSUE TITLE
addToWallet.js?

### ISSUE THREAD

**Issue by AleksAdamo** [IBM/assetTracking#6]
Hey there! The addToWallet.js is missing! Could someone fix it please :) ?

**Comment by ziadwagdy** [comment]
It is still missing.  
Could you find any solution?

**Comment by odrodrig** [comment]
Thanks for the heads up. I'll fix it.

**Comment by odrodrig** [comment]
Alright I submitted a fix that will fix the issue but am waiting for it to be merged. In short, the blockchain extension automatically adds the identity to the wallet for you so there is no need for the script, but a recent update to the extension moved where the wallet is stored. This broke the application as the apps could no longer find the wallet or the admin identity. 

Be sure to pull the latest changes once they go through.

**Comment by odrodrig** [comment]
Alright, it's merged now.

**Comment by Kevinjo81** [comment]
https://BNBCash.online/?ref=0x6FFAB26a8Af841458C872C57716D5e5dEEf3F3e7
