### ISSUE TITLE
Local filesystem wallet missing

### ISSUE THREAD

**Issue by pdhayden** [IBM/assetTracking#8]
I am following the steps as outlined in the readme file and I'm running into an issue with **Step 3** under [Configuring the local IoT Service](https://github.com/IBM/assetTracking#configuring-the-local-iot-service).

**Observed Behavior:**
i receive the following error:

**2019-08-13T23:27:20.501Z - error: [BaseWallet]: setUserContext: identity 'admin' isn't enrolled, or loaded**
(node:63712) UnhandledPromiseRejectionWarning: Error: identity 'admin' isn't enrolled, or loaded
    at FileSystemWallet.setUserContext (/Users/patrickhayden/developer/hyperledger/assetTracking/org1/application/iot_service/node_modules/fabric-network/lib/impl/wallet/basewallet.js:55:10)
(node:63712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Additional info:**
this seems to be caused by line 23 in **assetTracking/org1/application/iot_service/app.js** - 
`const wallet = new FileSystemWallet(homedir+'/.fabric-vscode/local_fabric_wallet/');`
It seems this directory structure does not exist on the dev machine I'm using. 

Thanks for the assist.

**Comment by odrodrig** [comment]
Thanks for the heads up! In a recent release of the IBM Blockchain Platform extension the location of the local wallet was changed which broke this app. I updated the line in the iot_service app to reflect this new location. Please pull the latest change and you should be good to go.

**Comment by pdhayden** [comment]
Works great! Thanks @odrodrig!

**Comment by narenltk** [comment]
Hey I just updated the path of the wallet just like you did mentioned and still i do face the error as shown below
![Untitled](https://user-images.githubusercontent.com/14790887/85253340-9317a980-b47b-11ea-967a-c020c9cd291e.png)
